### ISSUE TITLE
raspberry pi 5 script errors with "Debian version is not up to date"

### ISSUE THREAD

**Issue by karlh2000** [mcpat-it/NVMe#1]
I have a Pi 5B with an Argon one v3 case and NVME base. I installed a 4TB M.2 NVME, and can only use 2TB. I followed you instructions and get the error "Debian version is not up to date". I installed the latest 64 bit version using the imager app. The os-release file:

PRETTY_NAME="Raspbian GNU/Linux 12 (bookworm)"
NAME="Raspbian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

Looking at your code it is checking for version 12.4
Any help you can give me would be very much appreciated
Thank you
Karl

**Comment by mcpat-it** [comment]
@karlh2000 The latest version for me after `apt update` and `apt upgrade` was 12.4. Could you check with `uname -a`?

What you can do, change in the script from 12.4 to 12.0 and see what happens.

**Comment by karlh2000** [comment]
Changing the script worked, thanks much

**Comment by mcpat-it** [comment]
You are welcome
